apiVersion: v1
kind: Service
metadata:
    name: commentmanagementservicewebapi
spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: commentmanagementservicewebapi
