apiVersion: v1
kind: Service
metadata:
    name: commentmanagementservicewebapi
spec:
    type: LoadBalancer
    ports:
    - protocol: TCP
      containerPort: 80
      targetPort: 8080
    selector:
        app: commentmanagementservicewebapi
