apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: commentmanagementservicewebapi
    annotations:
        kubernetes.io/ingress.class: azure/application-gateway
        cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
  - hosts:
    - comment.management.polandcentral.cloudapp.azure.com
    secretName: comment-secret-name
  rules:
  - host: comment.management.polandcentral.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
              name: commentmanagementservicewebapi
              port:
                  number: 80
