apiVersion: v1
kind: Service
metadata:
    name: commentmanagementservicewebapi
spec:
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 443
      targetPort: 80
    selector:
        app: commentmanagementservicewebapi
